
--roles table 
CREATE TABLE roles (
  ID INTEGER NOT NULL,
  NAME varchar2(20) NOT NULL,
  CONSTRAINT roles_pk
    PRIMARY KEY (ID));

DROP SEQUENCE role_seq;
CREATE SEQUENCE role_seq START WITH 0 MINVALUE 0;


-- user info table
CREATE TABLE USER_INFO (
  ID INTEGER NOT NULL,
  EMAIL varchar2(40) NOT NULL,
  PHONE INTEGER NOT NULL,
  CONSTRAINT
    userinfo_pk PRIMARY KEY (ID));

DROP SEQUENCE userinfo_seq;
CREATE SEQUENCE userinfo_seq START WITH 0 MINVALUE 0;


--user table
CREATE TABLE users (
  ID INTEGER NOT NULL,
  FIRSTNAME varchar2(40) NOT NULL,
  LASTNAME varchar2(40) NOT NULL,
  USERINFO_ID INTEGER NOT NULL,
  CONSTRAINT
    users_pk PRIMARY KEY (ID),
  CONSTRAINT fk_userinfo
  FOREIGN KEY (USERINFO_ID)
    REFERENCES USER_INFO(ID));

DROP SEQUENCE users_seq;
CREATE SEQUENCE users_seq START WITH 0 MINVALUE 0;

-- user_role table
CREATE TABLE USER_ROLE (
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL);

-- student table
CREATE TABLE STUDENTS(
  ID INTEGER NOT NULL,
  NAME varchar2(40) NOT NULL,
  GROUPP varchar2(40) NOT NULL);